version: '3'

services:
  redis2:
    image: redis:latest
    container_name: redis-2
    ports:
      - '6379:6379'
    expose:
      - 6379
    networks:
      - mass-email
networks:
  mass-email:
    driver: bridge
